'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {asset} from '@/lib/asset';
export default function FridgeScene({door,exploded,thermal,air,running,selected,onSelect}:{door:boolean;exploded:boolean;thermal:boolean;air:number;running:boolean;selected:string;onSelect:(id:string)=>void}){
 const host=useRef<HTMLDivElement>(null);const live=useRef({door,exploded,thermal,air,running,selected,onSelect});useEffect(()=>{live.current={door,exploded,thermal,air,running,selected,onSelect};},[door,exploded,thermal,air,running,selected,onSelect]);const [error,setError]=useState('');
 useEffect(()=>{const el=host.current;if(!el)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch{queueMicrotask(()=>setError('이 브라우저에서 WebGL을 사용할 수 없습니다. 다른 탭의 계산·제어 기능은 사용할 수 있습니다.'));return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.setClearColor(0x142027,0);renderer.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(renderer.domElement);
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(35,1,.01,30);camera.position.set(1.65,1.18,2.2);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.46,0);controls.enableDamping=true;controls.minDistance=1;controls.maxDistance=4.2;controls.maxPolarAngle=Math.PI*.52;
 scene.add(new THREE.HemisphereLight(0xebfaff,0x40525d,2.7));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(2,3,3);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-2;key.shadow.camera.right=2;key.shadow.camera.top=2;key.shadow.camera.bottom=-2;key.shadow.bias=-.0001;scene.add(key);const rim=new THREE.DirectionalLight(0x62dacd,2);rim.position.set(-2,1,-2);scene.add(rim);
 const root=new THREE.Group();scene.add(root);const parts:THREE.Object3D[]=[];const moving:{o:THREE.Object3D;base:THREE.Vector3;offset:THREE.Vector3}[]=[];
 const material=(color:number,metalness=0,roughness=.5)=>new THREE.MeshStandardMaterial({color,metalness,roughness});const shellMat=material(0xcbd8da,.5,.3),insideMat=material(0xf1f4eb,.08,.46),black=material(0x18252c,.4,.35),glass=new THREE.MeshPhysicalMaterial({color:0x8edbd4,transparent:true,opacity:.4,roughness:.14,metalness:.1});const cold=material(0x66c8d4,.6,.3);
 function box(id:string,size:number[],pos:number[],mat:THREE.Material,parent:THREE.Object3D=root){const m=new THREE.Mesh(new THREE.BoxGeometry(...size as [number,number,number]),mat);m.position.set(...pos as [number,number,number]);m.castShadow=true;m.receiveShadow=true;m.userData.id=id;parent.add(m);parts.push(m);return m;}
 function move(o:THREE.Object3D,x:number,y:number,z:number){moving.push({o,base:o.position.clone(),offset:new THREE.Vector3(x,y,z)});}
 const left=box('cabinet',[.05,1,.52],[-.25,.53,0],shellMat);move(left,-.2,0,0);const right=box('cabinet',[.05,1,.52],[.25,.53,0],shellMat);move(right,.2,0,0);
 box('cabinet',[.45,.05,.52],[0,1.005,0],shellMat);box('cabinet',[.45,.05,.52],[0,.055,0],shellMat);const back=box('cabinet',[.45,.9,.05],[0,.53,-.235],insideMat);move(back,0,0,-.12);
 box('cabinet',[.444,.006,.44],[0,.086,0],insideMat);box('cabinet',[.444,.18,.19],[0,.16,-.125],insideMat);
 for(const y of [.34,.55,.76]){const shelf=box('shelves',[.432,.008,.39],[0,y,.025],glass);move(shelf,0,.05,.22);box('shelves',[.434,.014,.012],[0,y,.22],material(0xc1ced0,.7,.2));}
 const drawer=box('shelves',[.41,.13,.3],[0,.245,.07],glass);move(drawer,0,0,.22);
 for(const x of [-.205,.205])for(const z of [-.19,.19])box('cabinet',[.04,.045,.04],[x,.017,z],black);
 const hinge=new THREE.Group();hinge.position.set(.275,.5,.26);root.add(hinge);box('door',[.55,1,.06],[-.275,0,0],shellMat,hinge);box('door',[.446,.89,.015],[-.275,0,-.038],insideMat,hinge);box('door',[.018,.36,.035],[-.48,.06,.049],black,hinge);
 for(const y of [-.3,0,.29]){box('door',[.36,.09,.06],[-.275,y,-.08],glass,hinge);}
 const evaporator=box('evaporator',[.35,.25,.015],[0,.82,-.198],cold);move(evaporator,0,.17,-.2);
 const compressor=new THREE.Mesh(new THREE.SphereGeometry(.1,36,24),black);compressor.scale.set(1,.8,1);compressor.position.set(0,.15,-.27);compressor.userData.id='compressor';root.add(compressor);parts.push(compressor);move(compressor,0,-.03,-.32);
 function tube(id:string,points:number[][],color:number,r=.004,parent:THREE.Object3D=root){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p as [number,number,number])),false,'catmullrom',.1);const m=new THREE.Mesh(new THREE.TubeGeometry(curve,80,r,8,false),material(color,.55,.32));m.userData.id=id;parent.add(m);parts.push(m);return m;}
 const condenser=new THREE.Group();root.add(condenser);for(let j=0;j<10;j++){box('condenser',[.41,.008,.012],[0,.32+j*.059,-.283],black,condenser);if(j<9)tube('condenser',[[j%2?.2:-.2,.32+j*.059,-.283],[j%2?.22:-.22,.35+j*.059,-.283],[j%2?.2:-.2,.379+j*.059,-.283]],0x455459,.004,condenser);}move(condenser,0,0,-.3);
 tube('compressor',[[.07,.17,-.29],[.19,.18,-.31],[.2,.32,-.283]],0xdd8d50);tube('evaporator',[[-.2,.85,-.283],[-.23,.93,-.27],[-.2,.94,-.19],[0,.9,-.19]],0x68d0d1);
 const pcbGroup=new THREE.Group();pcbGroup.position.set(.15,.16,-.3);root.add(pcbGroup);box('main',[.115,.075,.008],[0,0,0],material(0x226b59),pcbGroup);box('main',[.027,.027,.006],[0,0,-.007],black,pcbGroup);for(let i=0;i<3;i++)box('main',[.018,.012,.015],[-.032+i*.032,-.025,-.01],insideMat,pcbGroup);move(pcbGroup,.2,0,-.35);
 const sensor=box('sensor',[.018,.03,.012],[.212,.69,.15],material(0xffc96d));const harness=tube('harness',[[.214,.69,.15],[.215,.69,-.18],[.215,.25,-.19],[.19,.16,-.3]],0xffc96d,.003);move(harness,.1,0,0);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.25}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(4,40,0x435c65,0x2c414a);grid.position.y=-.002;(grid.material as THREE.Material).transparent=true;(grid.material as THREE.Material).opacity=.3;scene.add(grid);
 const highlight=new THREE.BoxHelper(sensor,0xffc96d);scene.add(highlight);const dots:THREE.Mesh[]=[];for(let i=0;i<16;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.004,6,6),new THREE.MeshBasicMaterial({color:0x78ede5}));root.add(m);dots.push(m);}
 const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let down=[0,0];const pointerDown=(e:PointerEvent)=>{down=[e.clientX,e.clientY]};const pick=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=el.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(parts).find(h=>h.object.visible);if(hit)live.current.onSelect(hit.object.userData.id);};renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointerup',pick);
 const resize=new ResizeObserver(()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight);});resize.observe(el);
 let disposed=false;
fetch(asset('/design/cad-meshes.json')).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{parts:{id:string;positions:number[];indices:number[]}[]}>}).then(data=>{
 if(disposed)return;
 for(const o of parts)if(!['sensor','harness'].includes(o.userData.id))o.visible=false;
 const idMap:Record<string,string>={door_liner:'door',machine_compartment:'cabinet',shelf_1:'shelves',shelf_2:'shelves',shelf_3:'shelves',main_pcb:'main'};
 for(const part of data.parts){const id=idMap[part.id]||part.id;const isDoor=id==='door';const vertices=[];for(let i=0;i<part.positions.length;i+=3){vertices.push(part.positions[i]/1000-(isDoor?.275:0),part.positions[i+2]/1000-(isDoor?.5:0),-part.positions[i+1]/1000-(isDoor?.26:0));}
 const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setIndex(part.indices);geometry.computeVertexNormals();let mat:THREE.Material=id==='shelves'?glass:id==='evaporator'?cold:id==='compressor'||id==='condenser'?black:id==='main'?material(0x267e60):part.id==='door_liner'?insideMat:shellMat;
 if(part.id==='machine_compartment')mat=new THREE.MeshStandardMaterial({color:0x8dabb4,transparent:true,opacity:.15});
 const mesh=new THREE.Mesh(geometry,mat);mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData.id=id;(isDoor?hinge:root).add(mesh);parts.push(mesh);
 if(id==='shelves')move(mesh,0,0,.25);if(id==='compressor'||id==='condenser')move(mesh,0,0,-.3);if(id==='evaporator')move(mesh,0,.1,-.16);if(id==='main')move(mesh,.2,0,-.3);
 }
}).catch(()=>{if(!disposed)setError('CAD 메쉬를 읽지 못해 치수 기반 보조 모델을 표시합니다.');});
let raf=0;const start=performance.now();function animate(){raf=requestAnimationFrame(animate);const p=live.current;hinge.rotation.y+=((p.door?1.8:0)-hinge.rotation.y)*.09;hinge.position.z+=((p.exploded?.5:.26)-hinge.position.z)*.08;for(const m of moving)m.o.position.lerp(m.base.clone().addScaledVector(m.offset,p.exploded?1:0),.07);insideMat.color.set(p.thermal?new THREE.Color().setHSL(.55-Math.min(40,Math.max(0,p.air))*.009,.6,.55):0xf1f4eb);const chosen=parts.find(o=>o.userData.id===p.selected&&o.visible);highlight.visible=!!chosen;if(chosen){highlight.setFromObject(chosen);highlight.update();}const t=(performance.now()-start)/1000;dots.forEach((d,i)=>{d.visible=p.thermal&&p.running;d.position.set(.13*Math.sin(i*2.4),.2+((t*.13+i/16)%1)*.7,.07+.1*Math.cos(i*1.9));});controls.update();renderer.render(scene,camera);}animate();
 return()=>{disposed=true;cancelAnimationFrame(raf);resize.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',pointerDown);renderer.domElement.removeEventListener('pointerup',pick);scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose());}});renderer.dispose();renderer.domElement.remove();};
 },[]);
 return <div ref={host} className="scene" aria-label="회전과 확대가 가능한 1도어 냉장고 3D 모델">{error&&<p className="webgl-error">{error}</p>}</div>;
}
