'use client';
/* eslint-disable jsx-a11y/prefer-tag-over-role -- SVG charts use the image role for an accessible summary. */
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {Box,FileText,Play,Pause,RotateCcw,Download,DoorOpen,Layers,Scissors,ChevronRight,Snowflake} from 'lucide-react';
import ReferenceScene from '@/components/reference-scene';
import RefrigerantCircuit from '@/components/refrigerant-circuit';
import {useLocalFile} from '@/components/local-file';
import {referenceDefaults,referenceInitial,stepReference} from '@/lib/reference-simulation';
import type {Conditions} from '@/lib/reference-simulation';
import type {CycleTable} from '@/lib/simulation';
import './reference.css';
const source='https://www.truemfg.com/wp-content/uploads/true-media/spec-sheets/T-19-HC.pdf';
const parts:Record<string,[string,string,string]>={cabinet:['본체','도면 치수','폭 685.8 · 깊이 622.3 · 본체 높이 1,917.7 mm. 내벽 두께는 추정.'],door:['도어','도면 비례','1도어 · 우측 힌지 · 문 높이와 두께는 도면 비례로 재구성.'],handle:['매립 손잡이','사양 + 추정','12인치 손잡이. 단면과 매립 깊이는 추정.'],shelves:['철망 선반','사양 치수','3개 · 581.025 × 463.55 mm. 선재 굵기·설치 높이는 추정.'],grille:['하부 흡배기 그릴','도면 비례','하부 기계실 앞 루버. 개별 슬롯 형상은 재구성.'],castors:['캐스터','도면 치수','지름 63.5 mm · 바닥에서 본체까지 87.3125 mm.'],display:['상부 표시부','도면 비례','외부 온도 표시. 표시기와 스위치 위치·형상은 추정.'],compressor:['압축기','개략 형상','하부 응축 유닛. 압축기 외형·정확한 위치·성능맵은 미확인.'],condenser:['응축기','개략 형상','하부 응축 유닛. 코일·배관 세부 도면은 미확인.'],evaporator:['증발기','개략 형상','상부 배치와 치수는 추정. 상세 유로·팬 형상은 미확인.']};
export default function ReferencePage(){
 const hasSpec=useLocalFile('/reference/manufacturer-spec.pdf');
 const [tab,setTab]=useState('circuit'),[selected,setSelected]=useState('cabinet'),[exploded,setExploded]=useState(false),[section,setSection]=useState(false),[view,setView]=useState('iso');
 const [c,setC]=useState<Conditions>({...referenceDefaults}),[state,setState]=useState(referenceInitial),[playing,setPlaying]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState('');
 const sim=useRef(referenceInitial()),config=useRef(c),table=useRef<CycleTable|null>(null);useEffect(()=>{config.current=c;},[c]);
 const sync=()=>setState({...sim.current,history:[...sim.current.history]});
 useEffect(()=>{fetch('/reference/cycle-table.json').then(r=>{if(!r.ok)throw Error();return r.json() as Promise<CycleTable>;}).then(t=>{if(t.refrigerant!=='R290'||!t.points?.length)throw Error();table.current=t;setReady(true);}).catch(()=>setError('R290 계산 데이터를 불러오지 못했습니다.'));},[]);
 useEffect(()=>{if(!playing)return;let last=performance.now(),frame=0;const loop=(now:number)=>{if(table.current)stepReference(sim.current,config.current,table.current,Math.max(0,Math.min((now-last)/1000,.25))*120);last=now;sync();frame=requestAnimationFrame(loop);};frame=requestAnimationFrame(loop);return()=>cancelAnimationFrame(frame);},[playing]);
 function advance(seconds:number){if(table.current){stepReference(sim.current,c,table.current,seconds);sync();}}
 function reset(){setPlaying(false);sim.current=referenceInitial();setC({...referenceDefaults});sync();}
 function csv(){const blob=new Blob(['seconds,air_C,food_C\n'+state.history.map(x=>`${x.t},${x.air},${x.food}`).join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='T19-reference-model-estimates.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const select=parts[selected]||parts.cabinet;
 const path=(key:'air'|'food')=>state.history.map((x,i)=>`${i?'L':'M'}${40+((x.t-state.history[0].t)/Math.max(60,state.t-state.history[0].t))*680},${140-(Math.max(-5,Math.min(45,x[key]))+5)*2.4}`).join(' ');
 return <main className="ref-app"><header className="ref-header"><div><span className="ref-kicker">REAL PRODUCT / DRAWING RECONSTRUCTION</span><h1>True <b>T-19-HC</b></h1></div><div className="ref-header-actions"><Link href="/lab">이전 가상 설계</Link><a className="ref-button" href="/reference/reference-package.zip" download><Download size={16}/>설계 묶음</a></div></header>
 <div className="ref-banner">제조사 공개 도면 기반 <span>·</span> 2024년 1월 사양서, 2페이지 상세 도면 기준 <span>·</span> 내부 부품은 확인 범위별 표시</div>
 <div className="ref-workspace"><aside className="ref-sidebar"><h2>구성 부품 <span>10</span></h2>{Object.entries(parts).map(([id,p])=><button key={id} className={selected===id?'selected':''} onClick={()=>{setSelected(id);setTab('model')}}><Box size={15}/>{p[0]}{selected===id&&<ChevronRight size={14}/>}</button>)}<div className="ref-detail"><small>{select[1]}</small><h3>{select[0]}</h3><p>{select[2]}</p></div><a href={source} target="_blank" rel="noreferrer"><FileText size={16}/> 제조사 원본 PDF ↗</a></aside>
 <section className="ref-center"><nav className="ref-tabs" aria-label="설계 보기">{[['circuit','냉매 · 배관'],['model','3D 설계'],['drawing','원본 도면 비교'],['simulation','냉각 실험'],['evidence','설계 근거']].map(([id,label])=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==='circuit'&&<RefrigerantCircuit ambient={c.ambient}/>}
 {tab==='model'&&<div className="ref-stage"><div className="ref-toolbar"><button className={c.door?'selected':''} onClick={()=>setC({...c,door:!c.door})}><DoorOpen size={15}/>문 {c.door?'닫기':'열기'}</button><button className={exploded?'selected':''} onClick={()=>setExploded(!exploded)}><Layers size={15}/>분해</button><button className={section?'selected':''} onClick={()=>setSection(!section)}><Scissors size={15}/>외함 숨김</button><select aria-label="시점" value={view} onChange={e=>setView(e.target.value)}><option value="iso">입체도</option><option value="front">정면</option><option value="side">우측면</option><option value="top">평면</option></select></div><ReferenceScene door={c.door} exploded={exploded} section={section} selected={selected} view={view} onSelect={setSelected}/><div className="ref-dim"><strong>685.8 × 622.3 × 2,005.0 <small>mm</small></strong><p>폭 × 본체 깊이 × 캐스터 포함 높이</p><span>후면 범퍼 포함 깊이 634.206 mm · 드래그 회전 / 스크롤 확대</span></div></div>}
 {tab==='drawing'&&<div className="ref-document"><h2>재구성에 사용한 상세 도면</h2><p>아래 원본 2페이지의 인치 값을 mm로 변환했습니다. 원본의 반올림된 mm 표기와 차이가 있습니다.</p>{hasSpec&&<iframe title="True T-19-HC 제조사 원본 도면" src="/reference/manufacturer-spec.pdf#page=2"/>}{hasSpec===false&&<p>제조사 사양서는 저작권 때문에 저장소에 포함하지 않습니다. 아래 링크에서 2페이지 원본을 확인하세요.</p>}<a href={source} target="_blank" rel="noreferrer">PDF가 표시되지 않으면 제조사 원본 열기 ↗</a><table><thead><tr><th>항목</th><th>도면 기준</th><th>3D 설계</th></tr></thead><tbody>{[['폭','27 in','685.800 mm'],['본체 깊이','24½ in','622.300 mm'],['본체 높이','75½ in','1,917.700 mm'],['전체 높이','78 15/16 in','2,005.013 mm'],['후면 범퍼 포함 깊이','24 31/32 in','634.206 mm']].map(row=><tr key={row[0]}>{row.map(v=><td key={v}>{v}</td>)}</tr>)}</tbody></table><p className="ref-note">자료 불일치: 같은 PDF 1페이지 사양표는 본체 높이 75¼ in와 캐스터 높이 3¼ in를 표기합니다. 이번 재구성은 2페이지 상세 도면을 선택했으며 두 값을 섞지 않았습니다.</p></div>}
 {tab==='simulation'&&<div className="ref-experiment"><span className="ref-kicker">R290 / REDUCED THERMAL MODEL</span><h2>문을 열면, 온도가 어떻게 변할까?</h2><p>실제 냉매 물성으로 계산합니다. 열손실·냉매 유량·제어값은 아래 가정값이며, 이 제품의 실측 성능 곡선은 아닙니다.</p><div className="ref-metrics"><div><span>내부 평균온도</span><strong>{state.air.toFixed(1)}<small>°C</small></strong></div><div><span>저장물 온도</span><strong>{state.food.toFixed(1)}<small>°C</small></strong></div><div><span>모델 소비전력</span><strong>{state.watts.toFixed(0)}<small>W</small></strong></div></div><svg viewBox="0 0 750 170" role="img" aria-label="시간에 따른 내부 및 저장물 온도"><path d="M40 20V140H720" fill="none" stroke="#56717c"/>{[0,10,20,30,40].map(v=><g key={v}><text x="5" y={144-(v+5)*2.4} fill="#a5b9c0" fontSize="12">{v}°</text><path d={`M40 ${140-(v+5)*2.4}H720`} stroke="#253c46"/></g>)}<path d={path('air')} fill="none" stroke="#6aead1" strokeWidth="2.5"/><path d={path('food')} fill="none" stroke="#efbe75" strokeWidth="2"/><text x="40" y="165" fill="#b5c9ce" fontSize="12">{(state.history[0].t/3600).toFixed(1)} h</text><text x="670" y="165" fill="#b5c9ce" fontSize="12">{(state.t/3600).toFixed(1)} h</text></svg><div className="ref-chart-key">● 내부 공기 <span>● 저장물</span></div><div className="ref-play"><button disabled={!ready} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'일시정지':'120배속 실행'}</button><button disabled={!ready||playing} onClick={()=>advance(3600)}>+1시간</button><button disabled={!ready||playing} onClick={()=>advance(86400)}>+24시간</button><button onClick={reset}><RotateCcw size={16}/>초기화</button><button onClick={csv}>CSV 저장</button></div><p>경과 {(state.t/3600).toFixed(2)} h · 누적 {(state.wh/1000).toFixed(3)} kWh · 기동 {state.cycles}회 · {c.power?(state.run?'냉각 중':'재기동 대기 / 온도 유지'):'전원 꺼짐'}</p><details><summary>계산식과 가정값</summary><p>공기·내장재 열용량 35 kJ/K, 저장물 3.5 kJ/(kg·K), 열교환계수 8 W/K. 개방 시 열손실계수 +18 W/K. 증발 −10°C, 응축 외기+15°C(30~65°C), 과열 5 K, 과냉 3 K, 등엔트로피 효율 0.60, 모터 효율 0.85.</p><p>냉각량 = 냉매 질량유량 × (증발기 출구 엔탈피 − 팽창 후 엔탈피). 온도 변화는 유입열·저장물 교환열·냉각량의 에너지 수지로 적분합니다. 가정 제어는 목표 ±0.7°C, 최소 ON 120초 / OFF 180초입니다. 성에·제상·냉매 충전량·배관 압력강하는 포함하지 않습니다.</p></details>{error&&<p role="alert">{error}</p>}</div>}
 {tab==='evidence'&&<div className="ref-document"><h2>무엇을 동일하게 만들었는가</h2><table><thead><tr><th>구분</th><th>이번 설계의 근거</th></tr></thead><tbody><tr><td>도면 치수 반영</td><td>외함 폭·깊이·높이, 캐스터 높이, 후면 범퍼 깊이</td></tr><tr><td>사양 반영</td><td>1도어, 철망 선반 3개, 매립 손잡이, R290 냉매와 하부 응축 유닛</td></tr><tr><td>형상 추정</td><td>도어 분할 높이, 내벽 두께, 내부 부품 위치, 루버·선재 상세</td></tr><tr><td>계산 가정</td><td>유량, 열손실, 부하, 제어 히스테리시스와 지연</td></tr><tr><td>자료 미확인</td><td>PCB 패턴, 하네스 핀맵, MCU·EEPROM 종류, 펌웨어, 압축기 성능맵</td></tr></tbody></table><p>STEP 파일은 공개된 외형 도면을 바탕으로 새로 만든 CAD입니다. 제조사가 배포한 내부 조립 CAD나 생산용 원도면은 아닙니다. 기존 가상 PCB·인버터 로직은 <Link href="/lab">이전 가상 설계</Link>에서만 볼 수 있습니다.</p><h3>참고 원본</h3><ul><li><a href={source} target="_blank" rel="noreferrer">True T-19-HC 사양서 · 1/24, p.2 상세 도면</a></li><li><a href="https://www.truemfg.com/product/t-19-hc/" target="_blank" rel="noreferrer">True 제품 페이지</a></li><li><a href="https://coolprop.org/fluid_properties/fluids/n-Propane.html" target="_blank" rel="noreferrer">CoolProp R290 물성식</a></li></ul><div className="ref-downloads"><a href="/reference/t-19-hc-reconstructed.step" download>재구성 STEP</a><a href="/reference/cad-verification.json" download>CAD 검증 결과</a><a href="/reference/cycle-table.json" download>R290 물성표</a></div></div>}
 </section><aside className="ref-controls"><h2><Snowflake size={17}/>실험 조건</h2><label>주변 온도 <b>{c.ambient}°C</b><input type="range" min="15" max="40" value={c.ambient} onChange={e=>setC({...c,ambient:+e.target.value})}/></label><label>목표 온도 <b>{c.target.toFixed(1)}°C</b><input type="range" min="1" max="3" step="0.1" value={c.target} onChange={e=>setC({...c,target:+e.target.value})}/></label><div className="ref-toggles">{[['door','문 열림'],['power','전원'],['light','실내등 스위치']].map(([key,label])=><label key={key}>{label}<input type="checkbox" checked={c[key as 'door'|'power'|'light']} onChange={e=>setC({...c,[key]:e.target.checked})}/></label>)}</div><p className="ref-note">실내등은 실제 사양처럼 별도 스위치로 조작합니다.</p><h3>미공개 성능의 가정값</h3><label>열손실 UA <b>{c.ua.toFixed(1)} W/K</b><input type="range" min="1" max="4" step=".1" value={c.ua} onChange={e=>setC({...c,ua:+e.target.value})}/></label><label>냉매 유량 <b>{(c.massFlow*1000).toFixed(2)} g/s</b><input type="range" min=".0004" max=".0012" step=".00005" value={c.massFlow} onChange={e=>setC({...c,massFlow:+e.target.value})}/></label><label>저장물 <b>{c.loadKg} kg</b><input type="range" min="1" max="40" value={c.loadKg} onChange={e=>setC({...c,loadKg:+e.target.value})}/></label><button className="ref-button ref-run" onClick={()=>setTab('simulation')}>냉각 실험 보기 <ChevronRight size={16}/></button><p className="ref-note">모델 상태 {c.power?(state.run?'냉각 중':'대기'):'전원 꺼짐'}<br/>계산은 냉각 실험 탭에서 시작합니다.</p></aside></div></main>;
}
