'use client';
import {useEffect,useRef,useState} from 'react';
import {Box, Cable, Cpu, Snowflake, Play, Pause, RotateCcw, DoorOpen, Layers, Thermometer, Download, ChevronRight, Zap, AlertTriangle, Power, ArrowUpRight, Check, X, Clock3, Activity, FileText, Settings2} from 'lucide-react';
import FridgeScene from '../../components/fridge-scene';
import {advance,defaults,event,exportCsv,initialState,interpolate} from '../../lib/simulation';
import type {CycleTable,Settings,State,Fault} from '../../lib/simulation';
const names:Record<string,string>={cabinet:'단열 캐비닛',door:'도어 어셈블리',shelves:'선반 · 수납실',evaporator:'증발기',condenser:'응축기',compressor:'압축기',sensor:'온도센서',main:'메인 제어 PCB',harness:'저전압 하네스'};
const details:Record<string,[string,string,string]>={cabinet:['550 × 580 × 1,000 mm','단열 두께 50 mm','명목 수납 120 L'],door:['우측 힌지 · 1도어','도어 두께 60 mm','도어 스위치 → MAIN DOOR_GPIO'],shelves:['투명 선반 3단','열부하 5 kg 가정','식품 비열 3,500 J/kg·K'],evaporator:['증발 온도 −15°C','과열도 5 K','R600a 냉매'],condenser:['응축 온도 = 외기 + 15 K','30–65°C 물성표 범위','팬 전력 5 W 가정'],compressor:['가상 가변속 압축기','정격 질량유량 0.45 g/s','명령 회전수 3,000 rpm'],sensor:['가상 NTC 센서','ADC_CABINET · 가상 입력','단선 시 압축기 보호 정지'],main:['가상 MCU · 3.3 V 논리','센서 / 도어 / UART / I²C','기판 파일은 저전압 I/O 연결용'],harness:['전원 / 접지 / 신호','센서 → 메인 → 인버터','실제 핀맵은 설계 파일 참조']};
const timeLabel=(s:number)=>`${Math.floor(s/3600).toString().padStart(2,'0')}:${Math.floor(s/60%60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
function download(name:string,text:string,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function Chart({s,target}:{s:State;target:number}){const h=s.history;const minT=Math.min(0,...h.map(p=>p.air),target-2),maxT=Math.max(30,...h.map(p=>Math.max(p.air,p.food)));const x=(t:number)=>42+(t-h[0].t)/Math.max(1800,s.time-h[0].t)*690,y=(v:number)=>140-(v-minT)/(maxT-minT)*114;const path=(k:'air'|'food')=>h.map((p,i)=>`${i?'L':'M'}${x(p.t).toFixed(1)},${y(p[k]).toFixed(1)}`).join(' ');return <svg viewBox="0 0 750 170" className="chart" aria-label="시간에 따른 고내와 식품 온도 그래프">{[0,1,2,3].map(i=>{const v=minT+(maxT-minT)*i/3;return <g key={i}><line x1="42" x2="734" y1={y(v)} y2={y(v)} stroke="#314048"/><text x="5" y={y(v)+4}>{v.toFixed(0)}°</text></g>})}<line x1="42" x2="734" y1={y(target)} y2={y(target)} stroke="#e7be7a" strokeDasharray="5 5"/><path d={path('food')} fill="none" stroke="#93a9b5" strokeWidth="2"/><path d={path('air')} fill="none" stroke="#65dace" strokeWidth="2.7"/>{[0,.5,1].map(f=><text key={f} x={42+690*f} y="163" textAnchor={f===1?'end':'start'}>{Math.round((h[0].t+Math.max(1800,s.time-h[0].t)*f)/60)}분</text>)}</svg>}
function Wiring({s,settings}:{s:State;settings:Settings}){const components=[['NTC 온도센서',settings.fault==='sensor'?'단선':`${s.air.toFixed(1)} °C`],['MAIN · 가상 MCU',s.phase],['INV · 가상 제어기',`${Math.round(s.rpm)} rpm`],['압축기 모델',`${s.cooling.toFixed(0)} W 냉각`]];return <div className="wiring-view"><div className="view-heading"><span className="eyebrow">SIGNAL PATH</span><h2>하나의 센서에서 냉각까지</h2><p>연결을 따라 신호와 제어 상태를 확인하세요.</p></div><div className="signal-chain">{components.map(([a,b],i)=><div className="signal-stage" key={a}><div className={'signal-node '+(s.alarm&&i<3?'fault':'')}><span className="node-number">0{i+1}</span>{i===0?<Thermometer/>:i===3?<Snowflake/>:<Cpu/>}<strong>{a}</strong><small>{b}</small></div>{i<3&&<div className={'connection '+(settings.fault==='communication'&&i===1?'broken':'')}><span>{['ADC_CABINET','UART TX / RX','속도 → 냉각량'][i]}</span><ChevronRight/></div>}</div>)}</div><div className="aux-nodes"><div><DoorOpen/><strong>도어 스위치</strong><span>DOOR_GPIO · {settings.door?'OPEN':'CLOSED'}</span></div><div><Cpu/><strong>가상 EEPROM</strong><span>I²C · SCL / SDA · 설정값 저장</span></div></div><div className="pin-table"><div className="table-title">논리 연결표 <span>저전압 참조 · 부품 번호와 패키지 미확정</span></div><table><thead><tr><th>연결</th><th>메인 핀</th><th>신호</th><th>현재 값</th></tr></thead><tbody><tr><td>J2 → 온도센서</td><td>ADC_CABINET</td><td>ADC / 3.3V</td><td>{settings.fault==='sensor'?'OPEN':`${s.air.toFixed(2)}°C`}</td></tr><tr><td>J4 → 도어 스위치</td><td>DOOR_GPIO</td><td>디지털 입력</td><td>{settings.door?'1 · OPEN':'0 · CLOSED'}</td></tr><tr><td>J5 → 인버터 논리 포트</td><td>TX / RX</td><td>가상 UART</td><td>{settings.fault==='communication'?'TIMEOUT':s.run?'RUN 3000':'STOP'}</td></tr><tr><td>J6 → 설정 메모리</td><td>SCL / SDA</td><td>I²C</td><td>{settings.target.toFixed(1)}°C</td></tr></tbody></table></div></div>}
export default function Home(){
 const sim=useRef(initialState());const config=useRef<Settings>({...defaults});const table=useRef<CycleTable|null>(null);const [s,setS]=useState<State>(()=>initialState());const [settings,setSettings]=useState<Settings>({...defaults});const [playing,setPlaying]=useState(false);const speed=useRef(120);const [rate,setRate]=useState(120);const [tab,setTab]=useState('structure');const [exploded,setExploded]=useState(false);const [thermal,setThermal]=useState(false);const [selected,setSelected]=useState('cabinet');const [modal,setModal]=useState(false);const [ready,setReady]=useState(false);const [message,setMessage]=useState('냉매 물성표 불러오는 중');const [saved,setSaved]=useState(false);const dialogRef=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(modal)dialogRef.current?.showModal();},[modal]);
 const refresh=()=>setS({...sim.current,history:[...sim.current.history],events:[...sim.current.events]});
 function change(p:Partial<Settings>){config.current={...config.current,...p};setSettings({...config.current});if(p.door!==undefined)event(sim.current,p.door?'도어 열림 · 외기 유입 증가':'도어 닫힘');if(p.power!==undefined)event(sim.current,p.power?'전원 복귀 · 저장 설정 사용':'가상 전원 OFF');if(table.current)advance(sim.current,config.current,table.current,1);refresh();}
 useEffect(()=>{fetch('/design/cycle-table.json').then(r=>{if(!r.ok)throw Error();return r.json() as Promise<CycleTable>}).then(t=>{if(!Array.isArray(t.points)||!t.points.length)throw Error();table.current=t;sim.current.cycle=interpolate(t,-15,40);setReady(true);setMessage('CoolProp 물성표 연결됨');refresh();}).catch(()=>setMessage('물성표를 불러오지 못했습니다. 새로고침해 주세요.'));},[]);
 useEffect(()=>{if(!playing)return;let last=performance.now(),paint=last,raf=0;function loop(now:number){const dt=Math.max(0,Math.min((now-last)/1000,.25))*speed.current;last=now;if(table.current)advance(sim.current,config.current,table.current,dt);if(now-paint>100){refresh();paint=now;}raf=requestAnimationFrame(loop);}raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[playing]);
 useEffect(()=>{
 const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;
 if(!context?.registerTool)return;
 const lifecycle=new AbortController();
 const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'read_refrigerator_state',title:'냉장고 상태 확인',description:'현재 가상 냉장고의 조건, 온도, 전력과 고장을 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({settings:config.current,time:sim.current.time,airC:sim.current.air,foodC:sim.current.food,powerW:sim.current.watts,phase:sim.current.phase})});
 register({name:'run_refrigerator_experiment',title:'냉장고 실험 실행',description:'조건을 적용하고 지정한 초만큼 같은 시뮬레이터를 전진시킵니다.',inputSchema:{type:'object',properties:{seconds:{type:'number',minimum:1,maximum:86400},ambient:{type:'number',minimum:15,maximum:40},target:{type:'number',minimum:2,maximum:8},door:{type:'boolean'}},required:['seconds'],additionalProperties:false},execute:(input:unknown)=>{
 const v=input as Record<string,unknown>;if(!v||typeof v!=='object'||Object.keys(v).some(k=>!['seconds','ambient','target','door'].includes(k)))throw Error('입력 항목 오류');
 if(typeof v.seconds!=='number'||!Number.isFinite(v.seconds)||v.seconds<1||v.seconds>86400)throw Error('시간 범위 오류');
 for(const [k,lo,hi] of [['ambient',15,40],['target',2,8]] as const)if(v[k]!==undefined&&(typeof v[k]!=='number'||!Number.isFinite(v[k])||v[k]<lo||v[k]>hi))throw Error('온도 범위 오류');
 if(v.door!==undefined&&typeof v.door!=='boolean')throw Error('도어 값 오류');if(!table.current)throw Error('물성표 준비 중');
 const patch:Partial<Settings>={};if(typeof v.ambient==='number')patch.ambient=v.ambient;if(typeof v.target==='number')patch.target=v.target;if(typeof v.door==='boolean')patch.door=v.door;
 setPlaying(false);change(patch);advance(sim.current,config.current,table.current,v.seconds);refresh();return {time:sim.current.time,airC:sim.current.air,foodC:sim.current.food,phase:sim.current.phase};}});
 return()=>lifecycle.abort();
},[]);
function reset(){setPlaying(false);sim.current=initialState();config.current={...defaults};setSettings({...defaults});if(table.current)sim.current.cycle=interpolate(table.current,-15,40);refresh();}
 function skip(){if(table.current){advance(sim.current,config.current,table.current,900);refresh();}}
 function save(){try{localStorage.setItem('mono120-eeprom',JSON.stringify({version:1,target:settings.target}));event(sim.current,`EEPROM 기록 · 목표 ${settings.target}°C`);setSaved(true);refresh();setTimeout(()=>setSaved(false),1800);}catch{setMessage('브라우저 저장 공간을 사용할 수 없습니다.');}}
 function power(){if(!settings.power){try{const v=JSON.parse(localStorage.getItem('mono120-eeprom')||'null');if(v?.version===1&&Number.isFinite(v.target)&&v.target>=2&&v.target<=8){change({power:true,target:v.target});return;}}catch{}}change({power:!settings.power});}
 const c=s.cycle;
 return <main className="app-shell"><header className="topbar"><div className="brand"><div className="brand-mark"><Snowflake size={23}/></div><div><strong>MONO<span>120</span></strong><small>REFRIGERATOR DESIGN LAB</small></div></div><div className="project-tag"><span className="status-dot"/>1도어 냉장고 <span className="divider">/</span> 기준 설계 01</div><button className="button subtle" onClick={()=>setModal(true)}><Download size={16}/>설계 파일</button></header>
 <div className="workspace"><aside className="sidebar"><div className="sidebar-title"><span>설계 탐색</span><span className="muted">01—09</span></div><div className="tree-root"><Box size={17}/> MONO 120 <span>120 L</span></div><nav aria-label="구성 부품">{Object.entries(names).map(([id,name],i)=><button key={id} className={'part-button '+(selected===id?'active':'')} onClick={()=>{setSelected(id);setTab('structure')}}><span className="tree-line"/><span className="part-index">{String(i+1).padStart(2,'0')}</span>{name}{selected===id&&<ChevronRight size={14}/>}</button>)}</nav><div className="part-detail"><span className="eyebrow">SELECTED COMPONENT</span><h3>{names[selected]}</h3>{details[selected].map(x=><p key={x}>{x}</p>)}</div><div className="sidebar-bottom"><span className="status-dot"/><div>가상 제품 프로젝트<small>실물 장치 연결 없이 실행</small></div></div></aside>
 <section className="center"><div className="workspace-title"><div><span className="eyebrow">VIRTUAL PROTOTYPE / 001</span><h1>1도어 냉장고</h1></div><span className="design-badge">R600a <span>·</span> 120 L</span></div><nav className="tabs" aria-label="설계 보기">{[['structure','구조 탐색',Box],['cycle','냉동 사이클',Snowflake],['wiring','배선 · 제어',Cable],['logic','운전 기록',Activity]].map(([id,label,Icon])=>{const I=Icon as typeof Box;return <button key={id as string} className={tab===id?'active':''} onClick={()=>setTab(id as string)}><I size={16}/>{label as string}</button>})}</nav>
 <div className="main-view">
 {tab==='structure'&&<><div className="scene-tools"><button className={exploded?'active':''} onClick={()=>setExploded(!exploded)}><Layers size={15}/>분해 보기</button><button className={thermal?'active':''} onClick={()=>setThermal(!thermal)}><Thermometer size={15}/>온도 표시</button></div><FridgeScene door={settings.door} exploded={exploded} thermal={thermal} air={s.air} running={s.run} selected={selected} onSelect={setSelected}/><div className="scene-label"><span className="eyebrow">{exploded?'EXPLODED ASSEMBLY':'ASSEMBLY VIEW'}</span><strong>{names[selected]}</strong><span>550 W × 580 D × 1,000 H mm · 응축기 돌출 +17.5 mm</span></div><div className="scene-hint">드래그하여 회전 · 스크롤하여 확대 · 부품 선택</div>{thermal&&<div className="thermal-legend"><span>0°C</span><i/><span>40°C</span><small>내함 평균온도 표시 · 유동 입자는 설명용</small></div>}</>}
 {tab==='wiring'&&<Wiring s={s} settings={settings}/>}
 {tab==='cycle'&&<div className="cycle-view"><div className="view-heading"><span className="eyebrow">VAPOR COMPRESSION / R600a</span><h2>열이 이동하는 네 단계</h2><p>CoolProp 물성표 기반 · 정상상태 사이클을 시간 모델에 연결</p></div><div className="cycle-grid">{[['01','압축기',`${(c?.pLowPa||0)/1e5<1?'저압':'흡입'} → 고압`,`${Math.round(s.watts)} W 입력`],['02','응축기',`${c?.tc.toFixed(0)||40}°C`,`${Math.round(s.run&&c?.h2?0.00045*(c.h2-c.h3)*s.rpm/3000:0)} W 방열`],['03','팽창부','등엔탈피 팽창','고압 액체 → 저압 혼합물'],['04','증발기','−15°C',`${s.cooling.toFixed(0)} W 냉각`]].map(([i,n,t,d])=><div className={'cycle-card cycle-'+i} key={i}><span>{i}<ArrowUpRight size={18}/></span><strong>{n}</strong><b>{t}</b><small>{d}</small></div>)}</div><div className="cycle-stats"><div><small>저압 / 절대압</small><strong>{((c?.pLowPa||0)/1e5).toFixed(2)} <em>bar</em></strong></div><div><small>고압 / 절대압</small><strong>{((c?.pHighPa||0)/1e5).toFixed(2)} <em>bar</em></strong></div><div><small>사이클 COP</small><strong>{c?.cop.toFixed(2)||'—'}</strong></div></div><p className="model-note">질량유량 0.45 g/s · 등엔트로피 효율 60% · 모터 효율 85%<br/>특정 압축기의 실측 성능표가 아닌 가정 모델입니다. 냉매 충전량을 산정하지 않습니다.</p></div>}
 {tab==='logic'&&<div className="logic-view"><div className="view-heading"><span className="eyebrow">VIRTUAL CONTROLLER</span><h2>판단부터 응답까지</h2><p>가상 MCU의 상태 전이와 명령 기록</p></div><div className="state-row">{['입력 확인','냉각 판단','인버터 명령','상태 응답'].map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong><Check size={15}/></div>)}</div><div className="logic-rules"><p><b>온도 제어</b>목표 +1°C에서 시작 / −1°C에서 정지</p><p><b>압축기 보호</b>최소 운전 120초 / 재시작 지연 180초</p><p><b>고장 처리</b>센서·통신·팬 고장 시 즉시 냉각 정지</p><p><b>설정 저장</b>EEPROM 저장 후 전원을 껐다 켜면 복원</p></div><div className="event-list">{s.events.map((e,i)=><div key={i}><time>{timeLabel(e.time)}</time><span>{e.text}</span></div>)}</div><p className="model-note">제어 동작 모델입니다. STM32 명령어·인터럽트 타이밍이나 인버터 스위칭 파형을 에뮬레이션하지 않습니다.</p></div>}
 </div><div className="timeline"><div className="timeline-heading"><h3>온도 추이 <span>TIME HISTORY</span></h3><div className="chart-legend"><span className="air-dot">고내</span><span className="food-dot">식품</span><span className="target-dot">목표</span><button aria-label="온도 기록 CSV 다운로드" onClick={()=>download('mono120-temperature.csv',exportCsv(s),'text/csv')}><Download size={15}/></button></div></div><Chart s={s} target={settings.target}/></div>
 <footer className="transport"><div className="transport-buttons"><button className="play-button" disabled={!ready} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={17}/>:<Play size={17}/>} {playing?'일시정지':'시뮬레이션 시작'}</button><button className="icon-button" aria-label="초기 상태로 재설정" onClick={reset}><RotateCcw size={17}/></button><button className="skip" disabled={!ready} onClick={skip}>+15분</button></div><div className="sim-time"><Clock3 size={15}/><strong>{timeLabel(s.time)}</strong></div><label className="speed-label">속도<select value={rate} onChange={e=>{const v=Number(e.target.value);speed.current=v;setRate(v)}}>{[1,60,120,600].map(x=><option key={x} value={x}>{x}×</option>)}</select></label></footer></section>
 <aside className="controls"><div className="panel-heading"><h2>시뮬레이션</h2><span className={'live-status '+(s.alarm?'fault':'')}>{s.alarm?'FAULT':playing?'RUNNING':'READY'}</span></div><div className="temperature-card"><span>고내 온도</span><div>{s.air.toFixed(1)}<small>°C</small></div><p><span className={'status-dot '+(s.run?'':'idle')}/>{s.phase}</p></div><div className="mini-metrics"><div><Zap size={16}/><strong>{s.watts.toFixed(0)}<small> W</small></strong><span>소비전력</span></div><div><Snowflake size={16}/><strong>{s.cooling.toFixed(0)}<small> W</small></strong><span>냉각 능력</span></div></div>
 <div className="control-section"><h3><Settings2 size={15}/>운전 조건</h3><label className="range-label" htmlFor="target">목표 온도<strong>{settings.target.toFixed(1)}°C</strong></label><input id="target" type="range" min="2" max="8" step=".5" value={settings.target} onChange={e=>change({target:Number(e.target.value)})}/><div className="range-end"><span>2°C</span><span>8°C</span></div><label className="range-label" htmlFor="ambient">주변 온도<strong>{settings.ambient}°C</strong></label><input id="ambient" type="range" min="15" max="40" step="1" value={settings.ambient} onChange={e=>change({ambient:Number(e.target.value)})}/><div className="range-end"><span>15°C</span><span>40°C</span></div><button className={'door-button '+(settings.door?'open':'')} onClick={()=>change({door:!settings.door})}><DoorOpen size={18}/><span>도어 {settings.door?'열림':'닫힘'}</span><i className={'switch '+(settings.door?'on':'')}/></button><div className="power-row"><button onClick={power} className={!settings.power?'off':''}><Power size={15}/>{settings.power?'전원 켜짐':'전원 꺼짐'}</button><button onClick={save}>{saved?<Check size={14}/>:<Cpu size={14}/>}설정 저장</button></div></div>
 <div className="control-section"><h3><AlertTriangle size={15}/>고장 주입</h3><label className="sr-only" htmlFor="fault">고장 종류</label><select id="fault" className="fault-select" value={settings.fault} onChange={e=>change({fault:e.target.value as Fault})}><option value="none">정상 운전</option><option value="sensor">온도센서 단선</option><option value="communication">인버터 통신 끊김</option><option value="fan">응축기 팬 정지</option></select>{s.alarm&&<div className="alarm"><AlertTriangle size={14}/>{s.alarm}<small>냉각 정지 · 고장 해제 후 180초 대기</small></div>}</div><div className="summary-metrics"><div><span>식품 온도</span><strong>{s.food.toFixed(1)}°C</strong></div><div><span>누적 사용량</span><strong>{s.wh.toFixed(1)} Wh</strong></div><div><span>압축기 회전수</span><strong>{Math.round(s.rpm).toLocaleString()} rpm</strong></div><div><span>운전 시작 횟수</span><strong>{s.cycles}회</strong></div></div><button className="model-link" onClick={()=>setModal(true)}><FileText size={14}/>모델 가정과 설계 자료<ChevronRight size={14}/></button><p className="connection-state"><span className={ready?'status-dot':'status-dot idle'}/>{message}</p></aside></div>
 {modal&&<dialog ref={dialogRef} className="modal" aria-labelledby="model-title" onCancel={()=>setModal(false)}><button className="modal-close icon-button" aria-label="닫기" onClick={()=>setModal(false)}><X/></button><span className="eyebrow">DESIGN PACKAGE / REV 01</span><h2 id="model-title">설계를 열어보세요.</h2><p>120L급 단일 도어 냉장고의 기준 설계와 계산 데이터입니다.</p><div className="download-grid"><a href="/design/one-door-120l.step" download><Box/>기구 설계 STEP<Download size={16}/></a><a href="/design/harness.html" target="_blank" rel="noreferrer"><Cable/>하네스 결선도<ArrowUpRight size={16}/></a><a href="/design/virtual-io-carrier.kicad_pcb" download><Cpu/>저전압 I/O 참조 기판<Download size={16}/></a><a href="/design/design-package.zip" download><Download/>전체 설계 패키지<Download size={16}/></a></div><h3>무엇을 계산하나요?</h3><ul><li>R600a 물성: CoolProp에서 계산한 48개 상태 조합을 보간합니다.</li><li>고내·내장재 등가 열용량 20 kJ/K, 식품 5 kg의 두 온도 모델입니다.</li><li>닫힌 도어 열관류 0.7 W/K, 열린 도어 추가 12 W/K를 가정합니다.</li><li>가상 제어기는 ±1°C 히스테리시스와 압축기 재시작 지연을 실행합니다.</li></ul><h3>모델 범위</h3><p>3D는 부품 배치와 평균온도를 표시합니다. 3D CFD, 결로·성에·제상, 냉매 충전량, 실제 압축기 맵, 고전압 인버터 회로는 포함하지 않습니다. PCB는 커넥터 간 배선이 있는 I/O 참조 기판이며 MCU·전력부가 실장된 완성 제어보드는 아닙니다. 가상 마이컴은 기능 모델이며 실제 칩의 바이너리를 실행하지 않습니다.</p><div className="model-sources"><a href="https://coolprop.org/coolprop/python-cycles.html" target="_blank" rel="noreferrer">CoolProp 사이클 계산 ↗</a><button onClick={()=>download('mono120-session.json',JSON.stringify({settings,state:sim.current},null,2))}>현재 실험 JSON 저장</button></div></dialog>}
 </main>
}
